server:
  port: 8080
spring:
  profiles:
    active: default
  #  DB??
  datasource:
    url: jdbc:postgresql://43.200.202.110:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: taeseok
    password: 1234

  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
